### ISSUE TITLE
When Breaking Dark oak or oak leaves with fist instead of dropping loot or nothing it drops the leaf block

### ISSUE THREAD

**Issue by guestuser69420** [Wondiws98/better-apple-drop#1]
When Breaking Dark oak or oak leaves with fist instead of dropping loot or nothing it drops the leaf block.
just in survival mode try to break oak leaves with your fist.
this bug ruins all features of the mod

**Comment by Wondiws98** [comment]
Thank you for reporting the issue, it is now fixed.

[Fixed version](https://modrinth.com/datapack/better-apple-drops/version/1.0.2)
